// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXj3fa-q0OvAVdYVX0SjAl61b_lSo55A',
    appId: '1:301397424959:web:8f03ce76aea8444976318a',
    messagingSenderId: '301397424959',
    projectId: 'gamers-arena-4ba5e',
    authDomain: 'gamers-arena-4ba5e.firebaseapp.com',
    databaseURL: 'https://gamers-arena-4ba5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamers-arena-4ba5e.firebasestorage.app',
    measurementId: 'G-H1DMTP7LPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXo2Gy_eGdUc1aohVkkKEphtDz5FNsiI',
    appId: '1:301397424959:android:19cd8c170ebe219576318a',
    messagingSenderId: '301397424959',
    projectId: 'gamers-arena-4ba5e',
    databaseURL: 'https://gamers-arena-4ba5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamers-arena-4ba5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAepuA4blLMv8_q2adUJ_wGCt3yt9Do8',
    appId: '1:301397424959:ios:01420795e2e86a6f76318a',
    messagingSenderId: '301397424959',
    projectId: 'gamers-arena-4ba5e',
    databaseURL: 'https://gamers-arena-4ba5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamers-arena-4ba5e.firebasestorage.app',
    iosBundleId: 'com.example.gamersGram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvXj3fa-q0OvAVdYVX0SjAl61b_lSo55A',
    appId: '1:301397424959:web:c2e35e0d2d903c8e76318a',
    messagingSenderId: '301397424959',
    projectId: 'gamers-arena-4ba5e',
    authDomain: 'gamers-arena-4ba5e.firebaseapp.com',
    databaseURL: 'https://gamers-arena-4ba5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gamers-arena-4ba5e.firebasestorage.app',
    measurementId: 'G-P83S6V6TH0',
  );
}
